language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock

directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

jdk:
  - openjdk11

notifications:
  email:
    - eranbou@gmail.com

script:
- ./gradlew clean assemble test ktlintCheck
