#!/bin/bash
run_in_testit_path () {
    path=`dirname "$(greadlink -f "${BASH_SOURCE%/*}/testit")"`
    cd $path > /dev/null
    echo -e `$1`
    cd - > /dev/null
}

if [ $# -ne 0 ]
  then
    target=`realpath "$1"`
    run_in_testit_path "./gradlew run -q --console=plain --args '$target'"
  else
    run_in_testit_path "./gradlew run -q --console=plain"
fi
