#!/bin/bash
run_in_testit_path() {
    path=`dirname "$(greadlink -f "${BASH_SOURCE%/*}/testit")"`
    cd $path > /dev/null
    eval "$1"
    cd - > /dev/null
}

trim() {
    local trimmed="$1"

    while [[ $trimmed == ' '* ]]; do
       trimmed="${trimmed## }"
    done
    while [[ $trimmed == *' ' ]]; do
        trimmed="${trimmed%% }"
    done

    echo "$trimmed"
}

if [ $# -ne 0 ]
  then
    target=`realpath "${@:$#}"`
    all_but_last_args=${*%${!#}}
    args="$(trim " $target $all_but_last_args ")"
    run_in_testit_path "./gradlew run -q --console=plain --args=\"${args}\""
  else
    run_in_testit_path "./gradlew run -q --console=plain"
fi
