name: 'Cache Build'
description: 'Cache build paths'
inputs:
  key:
    description: 'Cache key'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Cache build artifacts
      uses: actions/cache@v4
      with:
        path: |
          app/build
        key: ${{ inputs.key }}
        restore-keys: |
          ${{ inputs.key }}
