name: Test

env:
  cache-name: android-gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Cache build artifacts
        uses: ./.github/actions/cache-build-paths
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble with Gradle
        run: ./gradlew jar

  unit-tests:
    needs: setup

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Cache build artifacts
        uses: ./.github/actions/cache-build-paths
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test
